spring.application.name=payment-and-invoice-service
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_and_invoice_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.show-sql:false
spring.liquibase.enabled=true
spring.liquibase.change-log=changelog/changelog-master.xml

logging.level.org.springframework.security=DEBUG

psp.base-url:http://localhost:8081
psp.read-timeout-ms:10000
psp.connect-timeout-ms=5000
psp.endpoints.charge:http://localhost:8081/charges


